"""Add R2 storage columns to resumes table

Revision ID: 814393ea27ff
Revises: 923d3c7bb4d1
Create Date: 2025-10-15 01:05:11.848836

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '814393ea27ff'
down_revision: Union[str, None] = '923d3c7bb4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('storage_backend', sa.String(length=20), nullable=False))
    op.add_column('resumes', sa.Column('storage_url', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('storage_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'storage_key')
    op.drop_column('resumes', 'storage_url')
    op.drop_column('resumes', 'storage_backend')
    # ### end Alembic commands ###
