"""Add openai_tokens_used field to resume_analysis

Revision ID: 950fb2789d0d
Revises: 226b0b0920f1
Create Date: 2025-10-16 02:09:24.929999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950fb2789d0d'
down_revision: Union[str, None] = '226b0b0920f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_analyses', sa.Column('openai_tokens_used', sa.Integer(), nullable=True))
    op.drop_index('idx_resumes_user_hash', table_name='resumes')
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.create_index('idx_resumes_user_hash', 'resumes', ['user_id', 'file_hash'], unique=False)
    op.drop_column('resume_analyses', 'openai_tokens_used')
    # ### end Alembic commands ###
